# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-app:
    name: App Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
      CI: true
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use pnpm/Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm run build --if-present
      - name: Test build
        run: pnpm run test
