name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the API Docker image
        working-directory: ./code/recipe-book-api
        run: docker build . --file Dockerfile --tag recipe-book:$(date +%s)
      - name: Build the App Docker image
        working-directory: ./code/recipe-book-app
        run: docker build . --file Dockerfile --tag recipe-book:$(date +%s)
